# -----------------------------------------------------------------------------
# - DOCKERFILE
# - AUTOR: Brian Suarez | Eduardo Franco | Jhon Celemin | Wilman Ortiz
# - FECHA: 06-Octubre-2020
# - DESCRIPCION: Docker-compose que permite la creacion del
# -              contenedor con el servicio de comandos y queries de productos
# ------------------------------------------------------------------------------

version: '3.7'
services:
  server-security-services:
    image: wortiz1027/server-security-services:latest
    container_name: server-security-services
    hostname: server-security-services
    restart: always
    ports:
      - 9050:9050
      - 6150:6150
    environment:
      - CONFIG_SERVER=http://server-configuration-services:9090
      - EUREKA_SERVER=http://server-discovery-services:9091/eureka
      - EUREKA_HOST=10.39.1.85
      - DB_SECURITY_HOST=10.39.1.130     
    networks:
      - ntw_backend
networks:
  ntw_backend:
    external: true