-- MySQL Script generated by MySQL Workbench
-- Sat Oct 03 16:45:41 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema securitydb
-- -----------------------------------------------------
-- Base de datos que permite controlar la seguridad para mis servicios rest
DROP SCHEMA IF EXISTS `securitydb` ;

-- -----------------------------------------------------
-- Schema security
--
-- Base de datos que permite controlar la seguridad para mis servicios rest
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `securitydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `securitydb` ;

-- -----------------------------------------------------
-- Table `securitydb`.`tbl_sec_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `securitydb`.`tbl_sec_users` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `securitydb`.`tbl_sec_users` (
  `id_user` VARCHAR(255) NOT NULL,
  `cedula` BIGINT(255) NOT NULL,
  `nombres` VARCHAR(100) NOT NULL,
  `apellidos` VARCHAR(100) NOT NULL,
  `direccion` VARCHAR(255) NOT NULL,
  `fecha_nacimiento` DATETIME NOT NULL,
  `telefono` BIGINT(255) NOT NULL,
  `email` VARCHAR(512) NOT NULL,
  `username` VARCHAR(100) NOT NULL,
  `password` VARCHAR(512) NOT NULL,
  `enable` VARCHAR(45) NULL,
  `account_non_expired` VARCHAR(45) NULL,
  `credential_non_expired` VARCHAR(45) NULL,
  `account_non_locket` VARCHAR(45) NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `cedula_UNIQUE` ON `securitydb`.`tbl_sec_users` (`cedula` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `securitydb`.`tbl_sec_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `securitydb`.`tbl_sec_roles` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `securitydb`.`tbl_sec_roles` (
  `id_role` VARCHAR(255) NOT NULL,
  `role` VARCHAR(100) NULL,
  PRIMARY KEY (`id_role`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `securitydb`.`tbl_sec_user_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `securitydb`.`tbl_sec_user_roles` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `securitydb`.`tbl_sec_user_roles` (
  `user_id` VARCHAR(255) NOT NULL,
  `role_id` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`user_id`, `role_id`),
  CONSTRAINT `fk_roles`
    FOREIGN KEY (`role_id`)
    REFERENCES `securitydb`.`tbl_sec_roles` (`id_role`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `securitydb`.`tbl_sec_users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `securitydb`.`oauth_client_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `securitydb`.`oauth_client_details` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `securitydb`.`oauth_client_details` (
  `client_id` VARCHAR(255) NOT NULL,
  `resource_id` VARCHAR(255) NOT NULL,
  `client_secret` VARCHAR(255) NOT NULL,
  `scope` VARCHAR(255) NULL,
  `authorized_grant_types` VARCHAR(255) NULL,
  `web_server_redirect_uri` VARCHAR(255) NULL,
  `authorities` VARCHAR(255) NULL,
  `access_token_validity` BIGINT(10) NULL,
  `refresh_token_validity` BIGINT(10) NULL,
  `additional_information` VARCHAR(4096) NULL,
  `autoapprove` VARCHAR(255) NULL,
  PRIMARY KEY (`client_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `securitydb`.`oauth_client_token`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `securitydb`.`oauth_client_token` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `securitydb`.`oauth_client_token` (
  `token_id` VARCHAR(255) NOT NULL,
  `token` BLOB NULL,
  `authentication_id` VARCHAR(255) NULL,
  `user_name` VARCHAR(255) NULL,
  `client_id` VARCHAR(255) NULL,
  PRIMARY KEY (`token_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `securitydb`.`oauth_access_token`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `securitydb`.`oauth_access_token` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `securitydb`.`oauth_access_token` (
  `token_id` VARCHAR(255) NULL,
  `token` BLOB NULL,
  `authentication_id` VARCHAR(255) NULL,
  `user_name` VARCHAR(255) NULL,
  `client_id` VARCHAR(255) NULL,
  `oauth_access_tokencol` VARCHAR(255) NULL,
  `authentication` BLOB NULL,
  `refresh_token` VARCHAR(255) NULL)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `securitydb`.`oauth_refresh_token`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `securitydb`.`oauth_refresh_token` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `securitydb`.`oauth_refresh_token` (
  `token_id` VARCHAR(255) NULL,
  `token` BLOB NULL,
  `authentication` BLOB NULL)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `securitydb`.`oauth_code`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `securitydb`.`oauth_code` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `securitydb`.`oauth_code` (
  `code` VARCHAR(255) NULL,
  `authentication` BLOB NULL)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `securitydb`.`oauth_approval`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `securitydb`.`oauth_approval` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `securitydb`.`oauth_approval` (
  `user_id` VARCHAR(255) NULL,
  `client_id` VARCHAR(255) NULL,
  `scope` VARCHAR(255) NULL,
  `status` VARCHAR(10) NULL,
  `expired_at` DATE NULL,
  `last_modified_at` DATE NULL)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `securitydb`.`tbl_sec_users`
-- -----------------------------------------------------
START TRANSACTION;
USE `securitydb`;
-- password = Pica2020++ = $2a$10$1JhQJ58EH6CCzVwxCl1vcud5Eo3ivrlyT9hu2z28rbv.CA1yoWI/S
INSERT INTO `securitydb`.`tbl_sec_users` (`id_user`, `cedula`, `nombres`, `apellidos`, `direccion`, `fecha_nacimiento`, `telefono`, `email`, `username`, `password`, `enable`, `account_non_expired`, `credential_non_expired`, `account_non_locket`)
VALUES ('6e994309-c372-4670-a317-884af46b36e0', 7946135, 'root', 'admin', 'Calle 123', '1970-11-20', 301638457, 'root@touresbalon.com', 'root', '$2a$10$1JhQJ58EH6CCzVwxCl1vcud5Eo3ivrlyT9hu2z28rbv.CA1yoWI/S', 'true', 'true', 'true', NULL);

COMMIT;

-- -----------------------------------------------------
-- Data for table `securitydb`.`tbl_sec_roles`
-- -----------------------------------------------------
START TRANSACTION;
USE `securitydb`;
INSERT INTO `securitydb`.`tbl_sec_roles` (`id_role`, `role`) VALUES ('3e4556fe-05b2-11eb-99e0-4be5cd93732c', 'ROLE_ADMIN');
INSERT INTO `securitydb`.`tbl_sec_roles` (`id_role`, `role`) VALUES ('3e455870-05b2-11eb-99e1-0bd9d244f320', 'ROLE_USER');
INSERT INTO `securitydb`.`tbl_sec_roles` (`id_role`, `role`) VALUES ('618bdc1e-05b2-11eb-acd0-67a7ef0f42bc', 'ROLE_CLIENT');
INSERT INTO `securitydb`.`tbl_sec_roles` (`id_role`, `role`) VALUES ('3e4558ac-05b2-11eb-99e2-affede8f5a15', 'ROLE_GUEST');

COMMIT;

-- -----------------------------------------------------
-- Data for table `securitydb`.`tbl_sec_user_roles`
-- -----------------------------------------------------
START TRANSACTION;
USE `securitydb`;
INSERT INTO `securitydb`.`tbl_sec_user_roles` (`user_id`, `role_id`) VALUES ('6e994309-c372-4670-a317-884af46b36e0', '3e4556fe-05b2-11eb-99e0-4be5cd93732c');
INSERT INTO `securitydb`.`tbl_sec_user_roles` (`user_id`, `role_id`) VALUES ('6e994309-c372-4670-a317-884af46b36e0', '3e455870-05b2-11eb-99e1-0bd9d244f320');
INSERT INTO `securitydb`.`tbl_sec_user_roles` (`user_id`, `role_id`) VALUES ('6e994309-c372-4670-a317-884af46b36e0', '618bdc1e-05b2-11eb-acd0-67a7ef0f42bc');
INSERT INTO `securitydb`.`tbl_sec_user_roles` (`user_id`, `role_id`) VALUES ('6e994309-c372-4670-a317-884af46b36e0', '3e4558ac-05b2-11eb-99e2-affede8f5a15');

COMMIT;

-- -----------------------------------------------------
-- Data for table `securitydb`.`oauth_client_details`
-- -----------------------------------------------------
START TRANSACTION;
USE `securitydb`;
-- client_secret = 9430fd38-05b3-11eb-a999-c7e4bb44a691 = $2a$10$ZOrcCjbHPmkMWieuAbRxSevlh5ojSW7WgYacwhl4bSvlfyTatywQK
INSERT INTO `securitydb`.`oauth_client_details` (`client_id`, `resource_id`, `client_secret`, `scope`, `authorized_grant_types`, `web_server_redirect_uri`, `authorities`, `access_token_validity`, `refresh_token_validity`, `additional_information`, `autoapprove`)
VALUES ('5258f2f8-05b3-11eb-96f5-9f4a2df3ac0e', 'oauth/pica', '$2a$10$ZOrcCjbHPmkMWieuAbRxSevlh5ojSW7WgYacwhl4bSvlfyTatywQK', 'read,write', 'password,refresh_token,client_credentials', 'http://localhost:8086/MicroServices/', 'USER', 300, 600, '', 'false');

-- client_secret = c5aad3de-05b3-11eb-b5df-37ffdf85ceb0 = $2a$10$ZkiHduuF6fdRwpCSUyY/4um5AawbWC9M2ff4r49GyKr3ARAB1qAQO
INSERT INTO `securitydb`.`oauth_client_details` (`client_id`, `resource_id`, `client_secret`, `scope`, `authorized_grant_types`, `web_server_redirect_uri`, `authorities`, `access_token_validity`, `refresh_token_validity`, `additional_information`, `autoapprove`)
VALUES ('c2d81e6e-05b3-11eb-bc37-c39255d6522d', 'oauth/pica', '$2a$10$ZkiHduuF6fdRwpCSUyY/4um5AawbWC9M2ff4r49GyKr3ARAB1qAQO', 'read,write', 'password,refresh_token,client_credentials', 'http://localhost:8086/MicroServices/', 'USER', 300, 600, '', 'false');

COMMIT;