server:
  port: 9050

security:
  jwt:
    key-store: classpath:keystore/security-jwt.jks
    key-pair-alias: pica-oauth-jwt
    key-store-password: security
    key-pair-password: security

spring:
  #datasource:
  #  initialization-mode: always
  #  data: classpath:data.sql
  #  schema: classpath:schema.sql
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    database: MYSQL
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none # (create|none|update|create-drop|validate)
    show-sql: true
    properties:
      hibernate:
        cache:
          use_second_level_cache: false
          use_query_cache: false
        generate_statistic: true
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_SECURITY_HOST:localhost}:3306/securitydb?allowPublicKeyRetrieval=true&useSSL=false&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
    username: security
    password: security2020++
    platform: mysql
    initialization-mode: always
    hikari:
      initialization-fail-timeout: 0
      data-source-properties:
        cachePrepStmts: true
        useServerPrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useLocalSessionState: true
        useLocalTransactionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
      pool-name: securityPoolConetion
      connection-timeout: 60000
      maximum-pool-size: 5
  jmx:
    default-domain: startertest

  jackson:
    serialization:
      INDENT_OUTPUT: true

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.data: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: DEBUG
    co.edu.javeriana.servers: DEBUG